version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    builder: go
    binary: zoomdl
    goos:
      - windows
      - darwin
      - linux
dockers_v2:
  - id: linux-amd
    images:
      - "{{ .Env.REGISTRY }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  header: |
    ## ZoomDL release {{ .Tag }}

    Pull the container images from {{ .Env.REGISTRY }}:{{ .Version }}
    ```sh
    $ docker pull {{ .Env.REGISTRY }}:{{ .Version }}
    ```
