name: go-test
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.3'

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3

      - run: go test --cover ./...
